# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-05-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Kortnummer')),
            ],
            options={
                'verbose_name': 'Kort',
                'verbose_name_plural': 'Kort',
            },
        ),
        migrations.CreateModel(
            name='PersonOnTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Person på hold',
                'verbose_name_plural': 'Personer på hold',
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Navn')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personer',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Besøgt post')),
                ('pi', models.CharField(max_length=99, verbose_name='Raspberry Pi besøgt')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Poster',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Navn')),
            ],
            options={
                'verbose_name': 'Hold',
                'verbose_name_plural': 'Hold',
            },
        ),
        migrations.AddField(
            model_name='posts',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Teams'),
        ),
        migrations.AddField(
            model_name='persononteam',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Persons'),
        ),
        migrations.AddField(
            model_name='persononteam',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Teams'),
        ),
        migrations.AddField(
            model_name='cards',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Teams'),
        ),
    ]
